# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 100
    commit-message:
      prefix: ci
    cooldown: # Set a cooldown so that we don't get updates immediately
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      # Group all development updates in a single PR
      development-dependencies:
        dependency-type: 'development'
        applies-to: version-updates
      # Group minor production updates in a single PR
      production-minor:
        dependency-type: 'production'
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
      # Because major production updates aren't matched by any group, they will have individual PRs
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 100
    commit-message:
      prefix: ci
